### PR TITLE
Add support for /system/lxproc on Illumos

### PR DESCRIPTION
**Pull request by jdelStrother**
Illumos-based systems have relatively poor fork performance, so shelling out to ps to read the RSS isn't great.  However, they support variant of `/proc` in `/system/lxproc`.  How about the attached?

### CODE REVIEW

**Comment by jdelStrother** [comment]
Hm, it sounds like it's actually only available on SmartOS at the moment.  They supply VMs here - http://wiki.smartos.org/display/DOC/Download+SmartOS

**Comment by kwugirl** [comment]
Hi @jdelStrother! I've been going through and trying to update that various outstanding PRs on this repo--is this issue still a concern for you? If so, additional instructions or information on verifying this change would be greatly appreciated, as none of us on the team currently have experience with illumos or SmartOS, I believe.

**Comment by jdelStrother** [comment]
Hi there - yeah, it's still a concern for us, though we've been running my
fork in production without issues.   What do you need help with for
verifying it?

**Comment by kwugirl** [comment]
Cool, glad to hear that your fork has been running without any issues! When you said "it's actually only available on SmartOS at the moment," did you mean that `/system/lxproc` is only available on SmartOS of the various illumos distros?

**Comment by tkrajcar** [comment]
Closing for now, no response.

**Pull request closed without merging**
