### PR TITLE
Add instrumentation for the http.rb gem

### PR DESCRIPTION
**Pull request by tjsousa**
Based on [Talkdesk/newrelic_httprb](https://github.com/Talkdesk/newrelic_httprb), but also including running specs to test it under NewRelic's `HttpClientTestCases` harness.

Functional testing using `bundle exec rake test:multiverse[httprb]`.

Tested against all minor versions since `0.7.4` and all patch levels of the latest `2.0` branch.

### CODE REVIEW

**Comment by kenichi** [comment]
@tjsousa thank you for submitting this! We will be reviewing this and getting back to you soon.

**Comment by tjsousa** [comment]
Hey @kenichi, any news on this patch?

**Comment by kwugirl** [comment]
Hey @tjsousa ! @kenichi is out on vacation through next week but I believe he'd pulled this in to pull request it against our internal repo. We'll keep you posted of any further updates!

**Comment by tjsousa** [comment]
Thank you @kwugirl! 👍

**Comment by kenichi** [comment]
This has been released in version 3.16.3! Thanks, @tjsousa

**Pull request closed without merging**
