### PR TITLE
Support em-http-request

### PR DESCRIPTION
**Pull request by minsikzzang**
Support em-http-request

Support em-http-request in NewRelic agent
* https://github.com/igrigorik/em-http-request

Task
- [x] Add em-http-request support in newrelic
- [x] Add multiverse tests for em-http-request
- [x] Change set / get object in local fiber to local thread for ruby >= 2.0

Test Coverage
* ruby 1.8.7-p375 - partially passed (cannot perform full tests because of lack of fiber support)
* ruby 1.9.3-p484 - partially passed (cannot perform full tests because of issue with thread / fiber)
* ruby 2.0.0-p481 - fully passed
* ruby 2.1.1 - fully passed
* ruby 2.1.2 - fully passed

### CODE REVIEW

**Comment by jasonrclark** [comment]
Hi @minsikzzang. Wow, what an excellent contribution! Really appreciate how thoroughly you followed our conventions and testing. :sparkles: 

Since this is a significant new piece of instrumentation, it will take us some time to review, test and see how to get it worked in. We'll be in touch if we have any further feedback or questions on the code.

**Comment by minsikzzang** [comment]
Any update / news on this?

**Comment by jasonrclark** [comment]
Hi @minsikzzang. Sorry for the delay. I wanted to be sure we had things fully figured out before I got back to you.

In testing this, we ran into an issue with our system that's going to block us from merging. The agent can't presently represent overlapping, async operations. Given how fundamental that is to how `em-http-request` works, this is a big problem. This instrumentation would result in strangely mismatched times for transactions viewed in New Relic, which we can't do within the official agent.

This is a highly visible issue internally at New Relic, and people are working on it, but there's not a quick solution to let us gather this data correctly right now.

However, it would be awesome if we could repackage this as a third-party gem (`newrelic_em-http-request`?) Some example gems are linked at https://github.com/newrelic/extends_newrelic_rpm.  I would be very happy to help you get that set up if you're willing. My only request would be to mention the potential display issues in the README for overlapping requests so users are informed of the trade-offs.

One hangup about third-party gems has previously been the lack of multiverse test support outside the agent. In light of your awesome test coverage, I decided to write up support for pulling in rake test:multiverse on other gems. It will be in the upcoming 3.12.1 release of `newrelic_rpm`. At that point, you'll be able to keep in sync with the existing HTTP client tests in the agent, along with running the `em-http-request` specific tests you wrote.

You also make an excellent point about the fiber vs thread change in Ruby 2.0. Thank you for bringing it to our attention, and we will get that revised in the agent (although for the time being your extension gem would need to patch the agent).

Again, apologies for the time it took to get here, and I'm sorry we can't take the changes directly at this time. I hope you will consider packaging the work up as a gem. I'll comment back here when 3.12.1 with the multiverse testing support is available.

**Comment by minsikzzang** [comment]
Hi @jasonrclark , thanks for your comment. 

I'd be appreciate you setup the 3rd party repo, then I will push my change to there :)

Thanks
Min

**Comment by jasonrclark** [comment]
Cool. I'll get back in touch with some code after 3.12.1 ship with the necessary multiverse support. Thanks!

**Comment by jasonrclark** [comment]
Hey @minsikzzang. [newrelic_rpm 3.12.1 is finally out](https://rubygems.org/gems/newrelic_rpm/versions/3.12.1.298), so the support for running multiverse tests from a separate gem is now available.

I repackaged your code in a gem to make sure everything was working. You can download the result at https://www.dropbox.com/s/o8qr98drla9dpjg/newrelic_em-http-request.zip?dl=0. Please feel free to run with putting a repo up, updating the gemspec as you'd like, and publishing it.

Sorry for the awkward zip approach, but I wanted to be cautious of anyone interpreting a New Relic employee's fingerprints in the git history as meaning more about support for the gem than is intended.

We will definitely be in touch once the agent can support full async, and would love at that point to fold this instrumentation back into the agent itself. Thanks again for your work and patience on this! :sparkles:

**Pull request closed without merging**
