### PR TITLE
Fix warnings about instance variables not initialized

### PR DESCRIPTION
**Pull request by dx7**
Running tests with "RUBYOPT=-w" we can see many warning messages. I've tried resolve them without breaking anything.

### CODE REVIEW

**Comment by kwugirl** [comment]
Hey @dx7 thanks for sending this over! We've been taking a look at it and I wanted to check--this is for the tests that are run as `RUBYOPT=-w bundle exec rake test` right? We have a test suite called `multiverse` as well but I figured this probably wasn't for those tests there, please correct me if I'm wrong, though.

**Comment by dx7** [comment]
Yes, this is for the tests that are run as `RUBYOPT=-w bundle exec rake test`.

**Comment by kenichi** [comment]
This has now been released in [3.16.1](https://source.datanerd.us/ruby-agent/ruby_agent/blob/dev/CHANGELOG#L18-L23)! Thank you @dx7

**Comment by kenichi** [comment]
This has been included in the release of version 3.16.3 along with other warnings fixes! Thanks, @dx7

**Comment by dx7** [comment]
Thanks all you guys!

**Pull request closed without merging**
