### PR TITLE
Content Security Policy Level 2 support for NewRelic

### PR DESCRIPTION
**Pull request by fiscal-cliff**
This is very useful for those who use [twitter/secureheaders](https://github.com/twitter/secureheaders)

### CODE REVIEW

**Comment by tkrajcar** [comment]
Hi @fiscal-cliff, thanks for the contribution. We'll check it out and get back to you soon!

**Comment by tkrajcar** [comment]
Hi @fiscal-cliff! I've reviewed this change with our security team and unfortunately we can't accept it at this time. However, we are now tracking implementation of CSP header support on the browser agent injection as a feature and will hopefully have it shipped soon. It looks like you're trying to interface with Twitter's secureheaders gem -- that's pretty smart and definitely something we will include in our implementation. In the meantime, you're welcome to make local modifications to the agent and run it, so feel free to continue running your code if it's working for you!

**Comment by seanhandley** [comment]
I'd love to see a CSP-friendly implementation of New Relic. Disabling inline script protection isn't something we want to do, and we want to implement a policy for CSP.

Any movement on this @tkrajcar ?

**Comment by kwugirl** [comment]
Thanks for checking on this @seanhandley -- it’s good to know more about the demand for particular feature. Currently this ticket is still in our backlog, which isn’t particularly extensive, but it’s not yet on our roadmap of planned work for the next few months. I’ll add a note about your interest to it though, so that it’ll be taken into consideration for prioritization purposes.

**Comment by seanhandley** [comment]
Thanks @kwugirl. Not sure what the adoption rate is for CSP but I'd imagine it'll only increase over time.

**Comment by sgringwe** [comment]
@kwugirl is there any way to work around this shortcoming?

**Comment by kenichi** [comment]
Hi, @sgringwe. This PR specifically relates to the agent auto-injecting the browser instrumentation JS. The best work around is to paste that JS into your app where appropriate and configure the `<script>` tag attributes as you see fit. See also:

* https://discuss.newrelic.com/t/content-security-policy-and-browser-injection/2629/42
* https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/add-apps-new-relic-browser#copy-paste-app

**Pull request closed without merging**
